tupleList=((1,2),(1,2,4))
print(type(tupleList))
print(tupleList)
print(tupleList[0])
#--------------------------------------------
print('---------------------------')
sortedTupleList=sorted(tupleList)
print(type(sortedTupleList))
print(sortedTupleList)
